backend:
  name: git-gateway

media_folder: "site/static/uploads" # Folder where user uploaded files should go
public_folder: "uploads"

collections:
  - label: "Posts"
    name: "posts"
    folder: "_posts"
    create: true
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
